// Generated by tools/make-manifest.js (run `npm run build`). Optional: exam.html also has this list built in.
window.ExamCatalog = [
  {
    "file": "ai-realtest",
    "id": "ai-realtest",
    "title": "Intelligenza artificiale — Test completo",
    "description": "Ottanta domande sull'intelligenza artificiale: storia, machine learning, reti neurali, modelli linguistici, visione, dati e MLOps, etica e normativa, hardware. Mix di scelta singola e multipla, vero/falso, ordinamento, abbinamento, risposte numeriche e scenari.",
    "code": "AI-80",
    "version": "v1.0",
    "questionCount": 80,
    "topicCount": 8
  },
  {
    "file": "cinema-realtest",
    "id": "cinema-realtest",
    "title": "Cinema degli ultimi 50 anni — Test completo",
    "description": "Ottanta domande sulla filmografia dal 1976 a oggi: premi e festival, registi, attori, blockbuster e franchise, animazione, cinema italiano, colonne sonore e industria. Mix di scelta singola e multipla, vero/falso, ordinamento, abbinamento, risposte numeriche e scenari.",
    "code": "CINE-80",
    "version": "v1.0",
    "questionCount": 80,
    "topicCount": 8
  },
  {
    "file": "demo",
    "id": "demo",
    "title": {
      "en": "Engine Demo — all question types",
      "it": "Demo del motore — tutti i tipi di domanda"
    },
    "description": {
      "en": "A tiny exam that shows every question type, localized content, difficulty levels and custom modes.",
      "it": "Un piccolo esame che mostra ogni tipo di domanda, contenuti localizzati, livelli di difficoltà e modalità personalizzate."
    },
    "code": "DEMO",
    "version": "1.0",
    "questionCount": 15,
    "topicCount": 3
  },
  {
    "file": "managedServices",
    "id": "managedServices",
    "title": "HPE Managed Services Expertise Exam Simulator",
    "description": "Comprehensive validation bank for HPE Managed Services knowledge across ITSM, delivery, tooling, security, and partner programs.",
    "code": "MS-EXPERTISE",
    "version": "v1.0",
    "questionCount": 120,
    "topicCount": 5
  },
  {
    "file": "v31",
    "id": "v31",
    "title": "V31 Practice Test (Complete)",
    "description": "Complete V31 practice bank: 200 scenario-based and advanced questions plus 100 expert-level questions on AI fundamentals, HPE Private Cloud AI architecture and sizing, deployment and administration, NVIDIA and AI Essentials, MLIS/NIM, KAI Scheduler, air-gapped deployments, operations, edge AI and HPC.",
    "code": "V31",
    "version": "v2.0",
    "questionCount": 300,
    "topicCount": 26
  },
  {
    "file": "v31realtest",
    "id": "v31realtest",
    "title": "V31 Real Test",
    "description": "Thirty practice questions with the official answer rationales, transcribed from the V31 practice test document.",
    "code": "V31-REAL",
    "version": "v1.0",
    "questionCount": 30,
    "topicCount": 8
  }
];
