// Generated by tools/make-manifest.js (run `npm run build`). Optional: exam.html also has this list built in.
window.ExamCatalog = [
  {
    "file": "demo",
    "title": {
      "en": "Engine Demo — all question types",
      "it": "Demo del motore — tutti i tipi di domanda"
    },
    "description": {
      "en": "A tiny exam that shows every question type, localized content, difficulty levels and custom modes.",
      "it": "Un piccolo esame che mostra ogni tipo di domanda, contenuti localizzati, livelli di difficoltà e modalità personalizzate."
    },
    "code": "DEMO",
    "version": "1.0",
    "questionCount": 12,
    "topicCount": 3
  },
  {
    "file": "managedServices",
    "title": "HPE Managed Services Expertise Exam Simulator",
    "description": "Comprehensive validation bank for HPE Managed Services knowledge across ITSM, delivery, tooling, security, and partner programs.",
    "code": "MS-EXPERTISE",
    "version": "v1.0",
    "questionCount": 120,
    "topicCount": 5
  },
  {
    "file": "v31",
    "title": "V31 Practice Test",
    "description": "Practice test, scenario-based and advanced questions on AI fundamentals, HPE Private Cloud AI architecture and sizing, deployment and administration, NVIDIA and AI Essentials, operations, edge AI and HPC.",
    "code": "V31",
    "version": "v1.0",
    "questionCount": 200,
    "topicCount": 19
  },
  {
    "file": "v31advanced",
    "title": "V31 Advanced Practice Test",
    "description": "Expert-level scenario questions on HPE Private Cloud AI sizing, AI Essentials resource governance, MLIS/NIM model serving, air-gapped deployments, edge inferencing and HPC/AI.",
    "code": "V31-ADV",
    "version": "v1.0",
    "questionCount": 100,
    "topicCount": 7
  }
];
