// Generated by tools/build.js — do not edit.
const CACHE = 'examsim-61ed9005a2';
const ASSETS = ["./","exam.html","exams.js","manifest.webmanifest","icon.svg","demo.exam","managedServices.exam","v31.exam","v31realtest.exam"];
self.addEventListener('install', e => {
    e.waitUntil(caches.open(CACHE)
        .then(c => Promise.all(ASSETS.map(a => c.add(new Request(a, { cache: 'reload' })).catch(() => {})))));
});
// The page asks for the switch when the user clicks "Reload" in the "new version available" banner.
self.addEventListener('message', e => { if (e.data && e.data.type === 'SKIP_WAITING') self.skipWaiting(); });
self.addEventListener('activate', e => {
    e.waitUntil(caches.keys()
        .then(keys => Promise.all(keys.filter(k => k.startsWith('examsim-') && k !== CACHE).map(k => caches.delete(k))))
        .then(() => self.clients.claim()));
});
// Cache first, refreshed in the background (stale-while-revalidate); query strings are ignored for matching.
self.addEventListener('fetch', e => {
    const req = e.request;
    if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
    e.respondWith(caches.match(req, { ignoreSearch: true }).then(hit => {
        const net = fetch(req).then(resp => {
            if (resp && resp.ok) { const copy = resp.clone(); caches.open(CACHE).then(c => c.put(req, copy)); }
            return resp;
        }).catch(() => hit);
        if (hit) { e.waitUntil(net); return hit; }
        return net;
    }));
});
