#!/usr/bin/env node
// Bundles src/ into a single self-contained exam.html (works from file://, no server needed).
const fs = require('fs');
const path = require('path');
const { ROOT } = require('./exam-files.js');

const SRC = path.join(ROOT, 'src');

function jsFiles() {
    const dir = path.join(SRC, 'js');
    return fs.readdirSync(dir).filter(f => f.endsWith('.js')).sort().map(f => path.join(dir, f));
}
function cssFiles() {
    const dir = path.join(SRC, 'styles');
    return fs.readdirSync(dir).filter(f => f.endsWith('.css')).sort().map(f => path.join(dir, f));
}

function bundleJs() {
    return "(function () {\n'use strict';\n" + jsFiles().map(f => fs.readFileSync(f, 'utf8')).join('\n') + '\n})();\n';
}
function bundleCss() { return cssFiles().map(f => fs.readFileSync(f, 'utf8')).join('\n'); }

function build() {
    const { buildCatalog, writeCatalogFile } = require('./make-manifest.js');
    const catalog = buildCatalog();
    writeCatalogFile(catalog);
    let html = fs.readFileSync(path.join(SRC, 'template.html'), 'utf8');
    // function replacers: avoid "$&"-style special patterns in the inserted text
    html = html.replace('/*{{CSS}}*/', () => bundleCss());
    html = html.replace('/*{{CATALOG}}*/', () => 'window.ExamCatalogDefault = ' + JSON.stringify(catalog) + ';');
    html = html.replace('/*{{JS}}*/', () => bundleJs().replace(/<\/script/gi, '<\\/script'));
    fs.writeFileSync(path.join(ROOT, 'exam.html'), html);
    writeServiceWorker(html, catalog);
    return { bytes: Buffer.byteLength(html), exams: catalog.length };
}

// Service worker: caches the app shell and every exam file so the simulator works offline.
function writeServiceWorker(html, catalog) {
    const crypto = require('crypto');
    const assets = ['./', 'exam.html', 'exams.js', 'manifest.webmanifest', 'icon.svg'].concat(catalog.map(e => e.file + '.exam'));
    const hash = crypto.createHash('sha1').update(html);
    catalog.forEach(e => hash.update(fs.readFileSync(path.join(ROOT, e.file + '.exam'))));
    const version = hash.digest('hex').slice(0, 10);
    const sw = `// Generated by tools/build.js — do not edit.
const CACHE = 'examsim-${version}';
const ASSETS = ${JSON.stringify(assets)};
self.addEventListener('install', e => {
    e.waitUntil(caches.open(CACHE)
        .then(c => Promise.all(ASSETS.map(a => c.add(new Request(a, { cache: 'reload' })).catch(() => {}))))
        .then(() => self.skipWaiting()));
});
self.addEventListener('activate', e => {
    e.waitUntil(caches.keys()
        .then(keys => Promise.all(keys.filter(k => k.startsWith('examsim-') && k !== CACHE).map(k => caches.delete(k))))
        .then(() => self.clients.claim()));
});
// Cache first, refreshed in the background (stale-while-revalidate); query strings are ignored for matching.
self.addEventListener('fetch', e => {
    const req = e.request;
    if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
    e.respondWith(caches.match(req, { ignoreSearch: true }).then(hit => {
        const net = fetch(req).then(resp => {
            if (resp && resp.ok) { const copy = resp.clone(); caches.open(CACHE).then(c => c.put(req, copy)); }
            return resp;
        }).catch(() => hit);
        if (hit) { e.waitUntil(net); return hit; }
        return net;
    }));
});
`;
    fs.writeFileSync(path.join(ROOT, 'sw.js'), sw);
}

module.exports = { jsFiles, cssFiles, bundleJs, bundleCss, build };

if (require.main === module) {
    const r = build();
    console.log('built exam.html (' + Math.round(r.bytes / 1024) + ' KB), ' + r.exams + ' exam(s) in catalog');
}
